/**
 * ClarifyingQuestions Component
 *
 * Optional step before research to gather context.
 * Shows 2-4 questions generated by Haiku to refine the query.
 * User can answer or skip to proceed directly to research.
 *
 * @module components/ClarifyingQuestions
 */

'use client'

import { ChalkChat, ChalkArrowRight, ChalkLoading } from './ChalkIcons'

interface ClarifyingQuestionsProps {
  /** Questions to display */
  questions: string[]
  /** Current answers (one per question) */
  answers: string[]
  /** Update answers array */
  onAnswerChange: (index: number, value: string) => void
  /** Submit with answers */
  onSubmit: (e: React.FormEvent) => void
  /** Skip questions and proceed directly */
  onSkip: () => void
  /** Whether form is disabled (loading) */
  isLoading: boolean
}

/**
 * Clarifying questions form.
 *
 * @example
 * <ClarifyingQuestions
 *   questions={clarifyingQuestions}
 *   answers={answers}
 *   onAnswerChange={(i, v) => updateAnswer(i, v)}
 *   onSubmit={handleAnswersSubmit}
 *   onSkip={() => runFullResearch(originalQuery)}
 *   isLoading={isLoading}
 * />
 */
export function ClarifyingQuestions({
  questions,
  answers,
  onAnswerChange,
  onSubmit,
  onSkip,
  isLoading,
}: ClarifyingQuestionsProps) {
  return (
    <form onSubmit={onSubmit}>
      <div className="bg-paper-card rounded-xl border border-paper-accent/30 overflow-hidden chalk-frame">
        {/* Header */}
        <div className="p-3 bg-paper-surface/30 border-b border-paper-accent/20">
          <p className="text-sm text-paper-text flex items-center gap-2">
            <ChalkChat size={16} className="text-paper-accent" />
            Quick context for better results (optional)
          </p>
        </div>

        {/* Questions */}
        <div className="p-4 space-y-3">
          {questions.map((question, i) => (
            <div key={i}>
              <label className="block text-sm font-medium text-paper-text mb-1">
                {i + 1}. {question}
              </label>
              <input
                type="text"
                value={answers[i] || ''}
                onChange={(e) => onAnswerChange(i, e.target.value)}
                placeholder="Optional"
                className="w-full px-3 py-2 border border-paper-accent/30 rounded-lg text-sm bg-paper-bg text-paper-text placeholder:text-paper-muted"
              />
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="border-t border-paper-divider p-3 bg-paper-bg flex justify-between">
          <button
            type="button"
            onClick={onSkip}
            className="text-sm text-paper-muted hover:text-paper-text flex items-center gap-1"
          >
            Skip <ChalkArrowRight size={14} />
          </button>
          <button
            type="submit"
            disabled={isLoading}
            className="px-5 py-2 bg-paper-accent text-paper-bg rounded-lg text-sm font-medium disabled:opacity-50 inline-flex items-center gap-1.5"
          >
            {isLoading ? (
              <>
                <ChalkLoading size={14} /> Working...
              </>
            ) : (
              'Research'
            )}
          </button>
        </div>
      </div>
    </form>
  )
}
